version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .UserName }}'
    background = '#c386f1'
    foreground = '#ffffff'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    trailing_diamond = ''
    template = '   {{ .PWD }} '
    background = '#ff479c'
    foreground = '#ffffff'

    [blocks.segments.properties]
      folder_separator_icon = '  '
      home_icon = '~/'
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background = '#fffb38'
    foreground = '#193549'

    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    background = '#6CA35E'
    foreground = '#ffffff'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'go'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    background = '#8ED1F7'
    foreground = '#111111'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'julia'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    background = '#4063D8'
    foreground = '#111111'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    background = '#FFDE57'
    foreground = '#111111'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = false

  [[blocks.segments]]
    type = 'ruby'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    background = '#AE1401'
    foreground = '#ffffff'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    type = 'azfunc'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    background = '#FEAC19'
    foreground = '#ffffff'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    type = 'aws'
    style = 'powerline'
    powerline_symbol = ''
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']
    template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
    foreground = '#ffffff'

    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    template = '  '
    background = '#ffff66'
    foreground = '#111111'


  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}#e91e63{{ end }}']
    trailing_diamond = ''
    template = '<parentBackground></> 󰋑 '
    background = '#00897b'
    foreground = '#ffffff'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    leading_diamond = ''
    template = '  {{ .FormattedMs }}⠀'
    background = '#83769c'
    foreground = '#ffffff'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'battery'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    invert_powerline = true
    background_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} '
    background = '#f36943'
    foreground = '#ffffff'

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '

 
  

